### ISSUE TITLE
Credential does not persist

### ISSUE THREAD

**Issue by tommyyoon** [BruceBuckland/signin#2]
If you call getDetails again after logging in it prompt for username and password again. How can I make it so that it doesn't prompt for user name and password again?

**Comment by BruceBuckland** [comment]
@tommyyoon Sorry about that!  It turns out that you need a credentials provider in order for the User Pool to remain persistent.  
In AppDelegate after you get your pool if you do this:        
`        let credentialsProvider = AWSCognitoCredentialsProvider(regionType: .USEast1, identityPoolId: K.COGNITO_IDENTITY_POOL_ID, identityProviderManager:self.pool)`

And if you create a federated identities pool, and put the Identity Pool id into ConstantsAWS.swift like
`static let COGNITO_IDENTITY_POOL_ID = "put your id pool id here"`

Then the identity will remain persistent.  Furthermore if you do a: 
`credentialsProvider.getIdentityId().continuewithblock... (this will execute a block passing the result of the GetId API call)`
you will get your persistent (life long) id in your sucessblock. 
And you can use that id to:
`credentialsProvider.credentials().continuewithblock...(this will execute a block passing the result of the GetCredentialsForIdentityId API call)`

After that you can call other AWS services registered with that service configuration and they will use the credentials that you set up in your Federated Identities console (which creates 2 IAM roles)

I would push an update to this app, but I am going to take it down and replace it soon.  The way this one is set up it is very hard for me not to accidentally push AWS keys to GITHUB.  I have a new version set up to push.
 thanks for your report.

**Comment by tommyyoon** [comment]
Thanks for the reply!

I was doing that already in my appdelegate.

        let serviceConfiguration = AWSServiceConfiguration(region: .usEast1, credentialsProvider: nil)
        
        AWSServiceManager.default().defaultServiceConfiguration = serviceConfiguration
        
        let userPoolConfiguration = AWSCognitoIdentityUserPoolConfiguration(clientId: UserPool.ClientId, clientSecret: UserPool.ClientSecret, poolId: UserPool.PoolId)
        
        AWSCognitoIdentityUserPool.register(with: serviceConfiguration, userPoolConfiguration: userPoolConfiguration, forKey: "UserPool")
        
        self.pool = AWSCognitoIdentityUserPool(forKey: "UserPool")
        self.pool?.delegate = self
        
        let credentialsProvider = AWSCognitoCredentialsProvider(regionType: .usEast1, identityPoolId: IdentityPool.PoolId, identityProviderManager: self.pool)
        
        let defaultServiceConfiguration = AWSServiceConfiguration(region: .usEast1, credentialsProvider: credentialsProvider)
        
        AWSServiceManager.default().defaultServiceConfiguration = defaultServiceConfiguration
        AWSLambdaInvoker.register(with: defaultServiceConfiguration!, forKey: "Lambda")

My code basically calls two lambda functions one after the other and updates different sections in a tableview when the result returns. After I updated to Swift 3 and the AWSSDK 2.4.9 everything broke.

I was already setting the credentials provider as you can see above. Credentials not persisting is a simulator issue I think. I ran it on again on the device and it does not prompt me for username and password again.

Can you please clarify when you said?

> Furthermore if you do a: 
> credentialsProvider.getIdentityId().continuewithblock... (this will execute a block passing the result of the GetId API call)
> you will get your persistent (life long) id in your sucessblock. 
> And you can use that id to:
> credentialsProvider.credentials().continuewithblock...(this will execute a block passing the result of the GetCredentialsForIdentityId API call)

In what situation would I call getIdentityId or credentials methods?

Thanks again!

**Comment by BruceBuckland** [comment]
Be aware the IOS SDK changed substantially around 2.4 to really change everything (which is why the documentation on the AWS site is so confusing and wrong... it applies to the old IOS SDK version) so I am assuming you are using 2.4.7 or better.

If you turn on debugging and search the log for the word "target" you will find that various IOS SDK calls call various API (web api) calls.  The IOS SDK manages a lot of stuff, including retries and keeping tokens around, signing requests, etc.

So when you make calls to some services the API may be making the "GetCredentialsForId" call for you ("behind the scenes" as it were).  And that is why you may not have had to do it.

And the documentation makes none of this even remotely clear.

However... in order to call AWS Services like Lambda (whether services that are only allowed for your Auth role or for your UnAuth role (assuming you allow unauthenticated ID's)) you need to have credentials. And you can get those credentials via cognito (as opposed to storing keys in your app, a very bad idea) if you have an "IdentityId".  Using that IdentityId you can get credentials for it (these credentials by default last for 3600 seconds, and can be refreshed.  You can force that refresh (I think, not sure) by the credentialsProvider.refresh method.).  The way you get credentials for an IdentityId is to do the "GetCredentialsForIdentityId" API call which is done behind the scenes when you do the "credentialsProvider.credentials" call in the IOS SDK.

So you may not have to do those calls at all because the SDK does some of them behind the scenes.  For instance user.GetDetails does the "GetId" api call (so if you are only doing "Authenticated" access, then you may not need to do the credentialsProvider.getIdentityId because that just does the "GetId" which you have already done.  You can see that it is done in the log, or you can look at "credentialsProvider.identityId" property, and it will be set with your IdentityId.

So doing these calls may not be needed, but the underlying API calls do get done.

The time they become more important is when you are trying to deal with Unauthenticated use.  In that case you need to have a credentials provider but you don't want the IOS SDK requests to kick off "GetCredentialsForIdentityId" because that will kick off your AWSCognitoIdentityInteractiveAuthenticationDelegate (which uses your user pool and ask you for a password!)... so to have unauthenticated use actually work (this is not documented very well) there is a AWSAnonymousCredentialsProvider.  You make one of those, and don't associate it with a User Pool but just with the Identity Pool, and you can get credentials for that Identity Pool that are unauthenticated and it won't kick off the User Pool Authentication Delegate.  At this point I am really a bit out of my depth because I have only tried out a little bit (I made an anonServiceConfiguration, and anonCredentialsProvider and linked them, and was able to get an identityId without the AWSCognitoIdentityInteractiveAuthenticationDelegate kicking off, but I have more to learn there.  In the next version of the signin app I intend to make the app allow unauthenticated actions and authenticated actions, but I am not there yet.  None of the sample code uses unauthenticated access with AWSCognitoIdentityInteractiveAuthenticationDelegate.  The mobileHubHelper app does allow unauthenticated users to use AWS services, but it does this by NOT IMPLEMENTING the AWSCognitoIdentityInteractiveAuthenticationDelegate and for that matter by not implementing User Pools AT ALL!  

The mobile hub helper apps (which you make with the mobile hub, and then download to xcode) are a worthwhile thing to try, and the Mobile Hub Helper SDK API is in many ways a lot nicer than the IOS SDK.  (unfortunately since it is only documented in the .h files, and they only include headers when you download the mhh, so you need to download the mobile-hub-helper code from github to understand how it works.

**Comment by BruceBuckland** [comment]
If you call both lambda functions without doing the second in a continue block the second operates simultaneously with the first

The fist will ( should) cause the getcredentialsfirid call ( also asynchronous ) but I don't know how the SDK treats the second lambda call ... because it is still trying to get credentials for the first one... I don't think it will re-request credentials so I think it might fail you ( this is only conjecture what does the log say? )

If you need parallel calls to the two lambda, Maybe you call credentials directly first, then in a continue block with successful credentials you kick off the two lambda' that might work if the conjecture above is correct)

Bb

**Comment by BruceBuckland** [comment]
@tommyyoon I have abandoned this version (signin) and used a different approach in SignIn-awsmhh.  The new approach uses aws-mobile-hub-helper libraries to communicate with Cognito.  This approach really simplifies dealing with identities in an unauthenticated or authenticated state. See: [SignIn-awsmhh](https://github.com/BruceBuckland/SignIn-awsmhh). This version also supports unauth, auth, google, facebook and CognitoYourUserPools (AWSCognitoIdentityUserPool)

**Comment by tommyyoon** [comment]
Awesome! Thank you so much!
